### ISSUE TITLE
load scripts and cookies until decline is clicked

### ISSUE THREAD

**Issue by guyvanbael** [zessx/cookiesplease#3]
I'm trying to revert the functionality so that cookies are loaded by default, but cleared when clicking decline.

cookies set by gtm stay loaded (when i monitor in chrome devtools) when decline button is clicked. Altough my config says clearCookiesOnDeclien: true

After reloading the page or navigating to another page, the declined cookie is set so everything is fine after that.
Is it possible to clear the cookies on clicking decline and not refreshing the page or navigating to another page?

**Comment by zessx** [comment]
I doubt this will be possible, as it highly relies on the way each script will handle cookies. Clearing all cookies does NOT unload scripts like GTM, and they're free to re-create cookies later if you're not refreshing the page (and they will).

Plus, the opt-out is not an acceptable solution, legally speaking and regarding the GDPR laws (even if I perfectly understand the impact on analytics services).

You should have a look on [various ways to unload GTM](https://stackoverflow.com/a/59933975/1238019) (for your example) without a full reload, but this is not related to CookiesPlease.
